# Voice Assistant Configuration
app:
  name: "Lepida Voice Assistant"
  description: "A offline/online voice assistant powered by advanced AI technologies."
  version: "1.0.0"
  language: "id"  # Indonesian
  
audio:
  input:
    device_index: null  # Auto-detect microphone
    sample_rate: 16000
    channels: 1
    chunk_size: 1024
    format: "int16"
    
  output:
    device_index: null  # Auto-detect speaker
    sample_rate: 22050
    channels: 1
    
  processing:
    ambient_noise_duration: 1.0
    phrase_time_limit: 5.0
    timeout: 1.0

# Text-to-Speech Configuration
tts:
  primary_engine: "mms_tts"
  fallback_engines: ["coqui_tts", "piper_tts"]
  language: "id"
  voice_model: "facebook/mms-tts-ind"
  
# Speech-to-Text Configuration  
stt:
  primary_engine: "whisper_cpp"
  fallback_engines: ["google_stt"]
  language: "id"
  model_size: "base"
  
# Wake Word Detection
wakeword:
  enabled: true
  primary_engine: "porcupine"
  keywords: ["hey assistant", "halo asisten"]
  sensitivity: 0.5
  
# Sound Effects
soundfx:
  enabled: true
  engine: "beep"
  volume: 0.7
  
# Online Services
online:
  enabled: false
  google_stt_api_key: ""
  
# Logging
logging:
  level: "INFO"
  file: "logs/voice_assistant.log"
  console: true

frontend:
  enabled: true
  host: "localhost"
  port: 5000